"""empty message

Revision ID: 605724cb3e53
Revises: caa14b14b944
Create Date: 2024-02-09 18:54:42.711350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605724cb3e53'
down_revision = 'caa14b14b944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
